name: Java Maven CI with SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the source code (with submodules)
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Set up Java 17 using Temurin distribution
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache local Maven repository to speed up builds
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      # Debug: list all folders and files in the root directory to help investigate the path
      - name: Debug - List project structure
        run: ls -R

      # Verify if the pom.xml file exists in the correct directory from the root
      - name: Verify if pom.xml exists in ilegra/ilegra
        run: |
          if [ ! -f ilegra/ilegra/pom.xml ]; then
            echo "❌ pom.xml not found in ilegra/ilegra/"
            exit 1
          else
            echo "✅ pom.xml found in ilegra/ilegra/"
          fi

      # Build the project with Maven from the correct directory
      - name: Build with Maven
        working-directory: ./ilegra/ilegra
        run: mvn clean install --batch-mode

      # Run SonarCloud analysis from the correct directory
      - name: SonarCloud Scan
        working-directory: ./ilegra/ilegra
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN