name: SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache SonarCloud Packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-sonar

      - name: Cache Maven Packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: List Root Directory
        run: ls -la

      - name: List Target Directory
        run: ls -la target || echo "target directory does not exist"

      - name: Install Dependencies for Firefox
        run: |
          sudo apt-get update
          sudo apt-get remove -y firefox
          
          wget -O firefox-esr.tar.bz2 "https://ftp.mozilla.org/pub/firefox/releases/115.10.0esr/linux-x86_64/en-US/firefox-115.10.0esr.tar.bz2"
          tar -xjf firefox-esr.tar.bz2
          sudo mv firefox /opt/firefox115
          sudo ln -sf /opt/firefox115/firefox /usr/bin/firefox
          firefox --version
          
          wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.33.0-linux64.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/
          geckodriver --version

      - name: Build the Project
        run: xvfb-run -a mvn -B verify
        working-directory: ./ilegra/ilegra

      - name: List Target Directory after Build
        run: ls -la target || echo "target directory does not exist after build"

      - name: SonarCloud Scan
        run: xvfb-run mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: ./ilegra/ilegra