name: SonarCloud with Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build, Test and Analyze inside Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache SonarCloud Packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-sonar

      - name: Cache Maven Packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Build Docker Image
        run: docker build -t my-project-image .
        working-directory: ./ilegra/ilegra

      - name: Run Tests and SonarCloud Scan inside Docker
        run: |
          docker run --rm \
            -e DISPLAY=:99 \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
            -v ${{ github.workspace }}/ilegra/ilegra:/app \
            -w /app \
            my-project-image \
            bash -c "Xvfb :99 -screen 0 1920x1080x24 & sleep 3 && mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar"