name: Java Maven CI with SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the source code (with submodules)
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Set up Java 17 using Temurin distribution
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache local Maven repository to speed up builds
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      # Debug: list all folders and files
      - name: Debug - List project structure
        run: ls -R

      # Search for pom.xml in any subdirectory of labstech and set it as a variable
      - name: Find pom.xml in labstech
        id: find_pom
        run: |
          POM_PATH=$(find labstech -name pom.xml -print -quit)
          if [ -z "$POM_PATH" ]; then
            echo "❌ pom.xml not found in any subdirectory of labstech"
            exit 1
          else
            echo "✅ pom.xml found at $POM_PATH"
            echo "POM_PATH=$POM_PATH" >> $GITHUB_ENV
          fi

      # Build the project with Maven in the directory where pom.xml is found
      - name: Build with Maven
        working-directory: ${{ env.POM_PATH }}/..
        run: mvn clean install --batch-mode

      # Run SonarCloud analysis
      - name: SonarCloud Scan
        working-directory: ${{ env.POM_PATH }}/..
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN