name: Java Maven CI with SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('ilegra/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: 📂 Verify if pom.xml is present
        working-directory: ilegra
        run: |
          echo "Listing files in the current directory:"
          ls -la
          if [ ! -f pom.xml ]; then
            echo "❌ pom.xml not found in the expected directory!"
            exit 1
          else
            echo "✅ pom.xml found successfully!"
          fi

      - name: Build with Maven
        working-directory: ilegra
        run: mvn clean install --batch-mode

      - name: SonarCloud Scan
        working-directory: ilegra
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN